log_dir: ./logs-official-persona-experts
algorithm: rainbowplus
method: persona

target_llm:
  type_: gemini
  model_kwargs:
    model: gemini-2.5-flash
  sampling_params:
    temperature: 0.7
    top_p: 0.9
    max_tokens: 512

mutator_llm:
  type_: openai
  model_kwargs:
    model: gpt-4o
  sampling_params:
    temperature: 0.7
    top_p: 0.9
    max_tokens: 512

fitness_llm:
  type_: openai
  model_kwargs:
    model: gpt-4o
  sampling_params:
    temperature: 0.7
    top_p: 0.9
    max_tokens: 512

sample_prompts: ./data/harmbench.json
num_samples: 150
max_iters: 200
sim_threshold: 0.6
num_mutations: 10
fitness_threshold: 0.6
log_interval: 50
shuffle: true

mutation_strategy: persona
persona_config: configs/personas/experts.yml # Make sure to rest the expert.yml before running using experts-coldstart.yml
persona_type: RedTeamingExperts  # Generate red teaming expert personas

# Only include persona in archive
archive:
  path: 
    - ./configs/personas/experts.yml
  descriptor:
    - Persona 