log_dir: ./logs-persona-users
algorithm: rainbowplus
method: persona

target_llm:
  type_: openai
  model_kwargs:
    model: gpt-4o
  sampling_params:
    temperature: 0.7
    top_p: 0.9
    max_tokens: 512

mutator_llm:
  type_: openai
  model_kwargs:
    model: gpt-4o
  sampling_params:
    temperature: 0.7
    top_p: 0.9
    max_tokens: 512

fitness_llm:
  type_: openai
  model_kwargs:
    model: gpt-4o
  sampling_params:
    temperature: 0.7
    top_p: 0.9
    max_tokens: 512

sample_prompts: ./data/harmbench.json
num_samples: 15
max_iters: 10
sim_threshold: 0.6
num_mutations: 5
fitness_threshold: 0.6
log_interval: 10
shuffle: true
log_dir: logs-persona-users

mutation_strategy: persona
persona_config: configs/personas/users.yml # Clean up the file before running study.
persona_type: RegularAIUsers  # Generate regular AI user personas

# Only include persona in archive
archive:
  path: 
    - ./configs/personas/users.yml
  descriptor:
    - Persona 
